version: '3.8'

services:
  app:
    image: safiyu/ranthal:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./sqlite.db:/app/sqlite.db
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
